//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopciones
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Adopciones()
        {
            this.Seguimientos = new HashSet<Seguimientos>();
        }
    
        public int Id { get; set; }
        public int MascotaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string NombreSolicitante { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
        public string Documento { get; set; }
        public string Direccion { get; set; }
        public string Ciudad { get; set; }
        public string CodigoPostal { get; set; }
        public string TipoVivienda { get; set; }
        public string PropietarioInquilino { get; set; }
        public string PermiteMascotas { get; set; }
        public string TienePatio { get; set; }
        public string PersonasHogar { get; set; }
        public string HayNinos { get; set; }
        public string EdadesNinos { get; set; }
        public string ExperienciaMascotas { get; set; }
        public string QuePasoMascotas { get; set; }
        public string OtrasMascotas { get; set; }
        public string DescripcionOtrasMascotas { get; set; }
        public string HorasSola { get; set; }
        public string LugarDormir { get; set; }
        public string AccesoVeterinario { get; set; }
        public string GastosVeterinarios { get; set; }
        public string PlanMudanza { get; set; }
        public string Motivacion { get; set; }
        public string ComoSeEntero { get; set; }
        public bool AceptaTerminos { get; set; }
        public bool AceptaVisitas { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Seguimientos> Seguimientos { get; set; }
    }
}
