//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adopciones
    {
        public int Id { get; set; }
        public int MascotaId { get; set; }
        public Nullable<int> UsuarioId { get; set; }
        public string NombreSolicitante { get; set; }
        public string Email { get; set; }
        public string Telefono { get; set; }
        public System.DateTime FechaSolicitud { get; set; }
        public string Estado { get; set; }
    
        public virtual Mascotas Mascotas { get; set; }
    }
}
