//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MascotasPerdidas
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string TipoReporte { get; set; }
        public string TipoMascota { get; set; }
        public string Raza { get; set; }
        public string UbicacionReporte { get; set; }
        public string Descripcion { get; set; }
        public string FotoUrl { get; set; }
        public System.DateTime FechaReporte { get; set; }
        public string NombreReportante { get; set; }
        public string TelefonoContacto { get; set; }
        public string EmailContacto { get; set; }
        public string Estado { get; set; }
        public Nullable<int> UsuarioRegistraId { get; set; }
        public Nullable<System.DateTime> FechaResolucion { get; set; }
        public string Notas { get; set; }
    }
}
