//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permisos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Permisos()
        {
            this.RolPermisos = new HashSet<RolPermisos>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string Icono { get; set; }
        public int Orden { get; set; }
        public bool TieneCrud { get; set; }
        public string Descripcion { get; set; }
        public bool EstaActivo { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RolPermisos> RolPermisos { get; set; }
    }
}
