//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolPermisos
    {
        public int Id { get; set; }
        public string Rol { get; set; }
        public int PermisoId { get; set; }
        public bool TieneAcceso { get; set; }
        public bool PuedeCrear { get; set; }
        public bool PuedeLeer { get; set; }
        public bool PuedeActualizar { get; set; }
        public bool PuedeEliminar { get; set; }
        public System.DateTime FechaAsignacion { get; set; }
    
        public virtual Permisos Permisos { get; set; }
    }
}
