//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Integrador.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Seguimientos
    {
        public int Id { get; set; }
        public int AdopcionId { get; set; }
        public System.DateTime FechaSeguimiento { get; set; }
        public string TipoSeguimiento { get; set; }
        public string Observaciones { get; set; }
        public string EstadoMascota { get; set; }
        public Nullable<int> UsuarioRealizaSeguimientoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
    
        public virtual Adopciones Adopciones { get; set; }
    }
}
